require 'fileutils'

namespace :shaders do
  rootdir = File.expand_path('../', File.dirname(__FILE__))
  dir = File.expand_path('resources/shaders', rootdir)

  task :build_glsl do
    Dir.chdir dir do
      sh "bash ./build.sh"
    end
  end

  task inline_shaders: [:build_glsl] do
    contents = {}
    File.open File.join(rootdir, 'modules/graphics/mrblib/shaders.rb'), 'w' do |f|
      f.puts %(#
# Autogenerated #{Time.now.strftime('%D %T')}
# DO NOT MODIFY THIS FILE, ALL CHANGES WILL BE LOST.
# Mruby will not create very long strings, instead we create teh shaders by
# joining them line by line)

      f.puts "module Moon"
      f.puts "  DEFAULT_SHADERS = {"
      Dir.chdir File.join(dir, 'build') do
        Dir.glob("**/*.{frag,vert}") do |filename|
          puts "\t Adding Shader #{filename}"
          f.puts "    '#{filename}' => ["
          File.read(filename).each_line do |line|
            f.puts "      %(#{line.chomp}),"
          end
          f.puts %(    ].join("\\n"),)
        end
      end
      f.puts "  } # Moon::DEFAULT_SHADERS"
      f.puts "end"
    end
  end

  task build: [:build_glsl, :inline_shaders]

  task :clean do
    FileUtils::Verbose.rm_rf File.join(dir, 'build')
  end
end
